<?php

/**
 * @file registro_editar.phtml
 * @brief Generamos formulario según tipo de campo
 * @ingroup crud
 */

/** Saber si tenemos que cargar el código para el tratamiento de fechas */

$cargar_codigo_fechas_horas = FALSE;
$dir_codigo_fechas_horas    = '../'.GCM_DIR.'lib/int/databoundobject/ext/mugifly-jquery-simple-datetimepicker/';
$cargar_codigo_fechas       = FALSE;
$dir_codigo_fechas          = '../'.GCM_DIR.'lib/int/databoundobject/ext/jquery.datepick/';

?>

<?php if ( isset($this->displayHash["PROBLEMS"]) ) { ?>
<p class="error">Problemas con formulario</p>
<? } ?>

<br />

   <?php  // echo "CAMPOS: <pre>" ; print_r($this->campos) ; echo "</pre>"; // DEV  ?>

   <?php if ( isset($this->ID) ) { ?>
   <input type="hidden" name="id" value="<?=$this->ID?>" /> 
   <?php } ?>

   <?php foreach ( $this->campos as $campo => $relacion ) { ?>

   <?php if ( isset($this->campos[$campo]['oculto_form']) && $this->campos[$campo]['oculto_form'] == 1 ) { ?>
   <input type="hidden" name="<?=$campo?>" value="<?=$this->valores($campo)?>" /> 
   <?php continue; } ?>

   <?php if ( $relacion != 'ID' && $campo != "fecha_creacion" && $campo != "fecha_modificacion"  ) { ?>   

   <div class="caja_campo" id="caja_campo_<?=$campo?>">

   <?php if ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion'  ) { ?>

      <div class="caja_campo_titulo"><?=literal($this->campos[$campo]['tabla'])?>: </div>
      <select name="<?=$campo?>">
         <option><?=literal('Seleccionar')?></option>
         <option></option>
         <?php foreach ( $this->campos[$campo]['opciones'] as $res) { ?>
            <?php $count=0; ?>
            <?php foreach ( $res as $contenido ) { ?>
            <?php if ( $count == 0 ) $identificador = $contenido; ?>
            <?php if ( $count == 1 ) $nombre = $contenido; ?>
            <?php $count++; ?>
            <?php } ?>
            <option value="<?=$identificador?>"<?php if ( $identificador == $this->valores($campo) ) echo ' selected' ;?>>
            <?php echo $nombre; ?>
            </option>
         <?php } ?>
      </select>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion_varios'  ) { ?>

   <?php // Tenemos definido un campo que hace referencia a una tabla externa con relaciones multiples ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha' ) { ?>
   
   <?php $cargar_codigo_fechas[] = $campo; ?>
   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <input name="<?=$campo?>" id="<?=$campo?>" type="text" value="<?php echo$this->valores($campo)?>"/>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha_hora' ) { ?>
   
   <?php $cargar_codigo_fechas_horas[] = $campo; ?>
   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <input name="<?=$campo?>"  type="text" value="<?php if ( $this->valores($campo) ) { echo strftime("%Y-%m-%d %H:%M",strtotime($this->valores($campo))); } else { echo strftime("%Y-%m-%d %H:%M"); } ?>"/>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'pass_md5' ) { ?>
   
   <div class="caja_campo_titulo"><?=literal('contraseña')?>: </div>
   <input name="<?=$campo?>"  type="password" value=""/>
   </div>
   <div class="caja_campo" id="caja_campo_verificacion">
   <div class="caja_campo_titulo"><?=literal('verificación')?>: </div>
   <input name="verificacion"  type="password" value=""/>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'textarea'  ) { ?>

   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <textarea rows="<?=$this->campos[$campo]['rows']?>" cols="<?=$this->campos[$campo]['cols']?>" name="<?=$campo?>"><?=$this->valores($campo)?></textarea>

   <?php } else { ?>

   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <input name="<?=$campo?>" 
      <?php if ( isset($this->campos[$campo]['maxlength']) ) { ?>
      maxlength="<?=$this->campos[$campo]['maxlength']?>" 
      <?php } ?>
      <?php if ( isset($this->campos[$campo]['size']) ) { ?>
      size="<?=$this->campos[$campo]['size']?>" 
      <?php } ?>
      type="text" value="<?=$this->valores($campo)?>"/>

   <?php } ?>

   <div class="caja_campo_error">
      <?php if ( isset($this->displayHash['PROBLEMS'][$campo]) ) echo $this->displayHash['PROBLEMS'][$campo]; ?>
   </div>

   </div>

   <?php } ?>

   <?php } ?>

<?php

if ( $objeto_padre ) {

// Cargamos código para el tratamiento de fechas si se ha pedido

if ( $cargar_codigo_fechas_horas ) {

   $objeto_padre->ficheros_css["jquery.simple-dtpicker.css"] = $dir_codigo_fechas_horas."jquery.simple-dtpicker.css";
   $objeto_padre->librerias_js["jquery.simple-dtpicker.js"] = $dir_codigo_fechas_horas."jquery.simple-dtpicker.js";


   foreach ( $cargar_codigo_fechas_horas as $campo_fecha ) {
      $objeto_padre->codigo_js .= "
         $(function(){
            $('*[name=$campo_fecha]').appendDtpicker();
         });
         ";
      }

   }

if ( $cargar_codigo_fechas ) {

   $objeto_padre->ficheros_css['jquery.datepick.css'] = $dir_codigo_fechas.'jquery.datepick.css';
   $objeto_padre->codigo_js .= file_get_contents(dirname(__FILE__).'/../ext/jquery.datepick/jquery.datepick.js');

   foreach ( $cargar_codigo_fechas as $campo_fecha ) {
      $objeto_padre->codigo_js .= "
         $(function() {
            $('#".$campo_fecha."').datepick({dateFormat: 'yyyy-mm-dd'});
         });
         ";
      }

   }
} else {

   registrar(__FILE__,__LINE__,'No hay instancia del objeto padre','ERROR');

   }
?>
