<?php

/**
 * @file registro_editar.phtml
 * @brief Generamos formulario según tipo de campo
 * @ingroup crud
 * @ingroup plantilla_crud
 */

require_once(GCM_DIR.'lib/int/formato/lib/HTML.php');

/** Saber si tenemos que cargar el código para el tratamiento de fechas con horas.*/
$cargar_codigo_fechas_horas = FALSE;
/** Definimos directorio de los arhivos js necesarios. */
$dir_codigo_fechas_horas    = Router::$base.GCM_DIR.'lib/int/databoundobject/ext/mugifly-jquery-simple-datetimepicker/';
/** Saber si debemos cargar el código para las fechas. */
$cargar_codigo_fechas       = FALSE;
$dir_codigo_fechas          = Router::$base.GCM_DIR.'lib/ext/jquery/jquery-ui/';

?>

<?php if ( isset($this->displayHash["PROBLEMS"]) ) { ?>
<p class="error">Problemas con formulario</p>
<?php } ?>

<br />

   <?php  // echo "CAMPOS: <pre>" ; print_r($this->campos) ; echo "</pre>"; // DEV  ?>

   <?php if ( isset($this->ID) ) { ?>
   <?php echo HTML::form_hidden('id',$this->ID); ?>
   <?php } ?>

   <?php foreach ( $this->campos as $campo => $relacion ) { ?>

   <?php if ( isset($this->campos[$campo]['ignorar']) && $this->campos[$campo]['ignorar'] == 1 ) { ?>
   <?php continue; } ?>

   <?php if ( isset($this->campos[$campo]['oculto_form']) && $this->campos[$campo]['oculto_form'] == 1 ) { ?>
   <?php echo HTML::form_hidden($campo,$this->valores($campo)); ?>
   <?php continue; } ?>

   <?php if ( $relacion != 'ID' && $campo != "fecha_creacion" && $campo != "fecha_modificacion"  ) { ?>   

   <div class="caja_campo" id="caja_campo_<?php echo $campo?>">

   <?php if ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion'  ) { ?>

      <div class="caja_campo_titulo"><?php echo literal($this->campos[$campo]['tabla'],1)?></div>

      <?php echo HTML::form_select($campo, $this->campos[$campo]['opciones'],$this->valores($campo),literal('Seleccionar',1)); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion_varios'  ) { ?>

   <?php // Tenemos definido un campo que hace referencia a una tabla externa con relaciones multiples ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha' ) { ?>
   
   <?php $cargar_codigo_fechas[] = $campo; ?>

   <div class="caja_campo_titulo"><?php echo literal($campo,1)?></div>
   <?php echo HTML::form_fecha($campo,$this->valores($campo), array('placeholder' => "yyyy/mm/dd")); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha_hora' ) { ?>
   
   <?php $cargar_codigo_fechas_horas[] = $campo; ?>
   <div class="caja_campo_titulo"><?php echo literal($campo,1)?></div>
   <?php 
   $valor = ( $this->valores($campo) && $this->valores($campo) != '0000-00-00 00:00:00' ) 
               ? strftime("%Y-%m-%d %H:%M",strtotime($this->valores($campo))) 
               : strftime("%Y-%m-%d %H:%M"); 
   ?>
   
   <?php echo HTML::form_fecha($campo,$valor); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'pass_md5' ) { ?>
   
   <div class="caja_campo_titulo"><?php echo literal('contraseña',1)?></div>
   <?php echo HTML::form_pass($campo); ?>
   </div>
   <div class="caja_campo" id="caja_campo_verificacion">
   <div class="caja_campo_titulo"><?php echo literal('verificación',1)?></div>
   <?php echo HTML::form_pass('verificacion'); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'textarea'  ) { ?>

   <div class="caja_campo_titulo"><?php echo literal($campo,1)?></div>

   <?php echo HTML::form_text($campo
         ,$this->valores($campo)
         ,array('rows'=>$this->campos[$campo]['rows'],'cols'=>$this->campos[$campo]['cols'])
         ,0); 
   ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'enum'  ) { ?>

   <div class="caja_campo_titulo"><?php echo literal($campo,1)?></div>

   <?php echo HTML::form_enum($campo ,$this->valores($campo),FALSE,$this->campos[$campo]['opciones']); 
   ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'booleano'  ) { ?>

   <div class="caja_campo_titulo"><?php echo literal($campo,1)?></div>

   <?php echo HTML::form_bool($campo ,( $this->valores($campo) ) ? TRUE : FALSE ); 
   ?>

   <?php } else { ?>

   <?php $atr = FALSE ; ?>
   <?php if ( isset($this->campos[$campo]['maxlength']) ) $atr['maxlength'] = $this->campos[$campo]['maxlength'] ; ?>
   <?php if ( isset($this->campos[$campo]['size']) ) $atr['size'] = $this->campos[$campo]['size'] ; ?>

   <div class="caja_campo_titulo"><?php echo literal($campo,1)?></div>
   <?php echo HTML::form_text($campo
         ,$this->valores($campo)
         ,$atr); 
   ?>

   <?php } ?>

   <div class="caja_campo_error">
      <?php if ( isset($this->displayHash['PROBLEMS'][$campo]) ) echo $this->displayHash['PROBLEMS'][$campo]; ?>
   </div>

   </div>

   <?php } ?>

   <?php } ?>

<?php

if ( $objeto_padre ) {

// Cargamos código para el tratamiento de fechas si se ha pedido

if ( $cargar_codigo_fechas_horas ) {

   $objeto_padre->ficheros_css["jquery.simple-dtpicker.css"] = $dir_codigo_fechas_horas."jquery.simple-dtpicker.css";
   $objeto_padre->codigo_js .= file_get_contents(dirname(__FILE__).'/../ext/mugifly-jquery-simple-datetimepicker/jquery.simple-dtpicker.js');


   foreach ( $cargar_codigo_fechas_horas as $campo_fecha ) {

   // {
	//				'locale': 'es'
   //            ,'inline': true
   //            ,'dateFormat': 'd.m.y h.m'
	//			}
      $objeto_padre->codigo_js .= "
         $(function(){
            $('*[name=$campo_fecha]').appendDtpicker();
         });
         ";
      }

   }

if ( $cargar_codigo_fechas ) {

   $objeto_padre->ficheros_css['jquery-ui.css'] = $dir_codigo_fechas.'jquery-ui.min.css';
   // Se carga desde el módulo Temas.
   // $objeto_padre->codigo_js .= file_get_contents(GCM_DIR.'lib/ext/jquery/jquery-ui/jquery-ui.min.js');
   $idioma_calendario = ( Router::$i != 'en' ) ? Router::$i : FALSE ;
   if ( $idioma_calendario ) $objeto_padre->codigo_js .= 
     file_get_contents(GCM_DIR.'lib/int/databoundobject/ext/jquery/jquery-ui/lang/'.$idioma_calendario.'.js');

   foreach ( $cargar_codigo_fechas as $campo_fecha ) {
      $objeto_padre->codigo_js .= "
         $(function() {
            $('#".$campo_fecha."').datepicker({dateFormat: 'dd/mm/yy'});
         });
         ";
      }

   }
} else {

   registrar(__FILE__,__LINE__,'No hay instancia del objeto padre','ERROR');

   }
?>
