<?php

/**
 * @file registro_visualizar.phtml
 * @brief Plantilla por defecto para mostrar los registros individualmente
 * @ingroup crud
 * @ingroup plantilla_crud
 */

require_once(GCM_DIR.'lib/int/formato/lib/HTML.php');

?>

<?php if ( isset($this->displayHash["PROBLEMS"]) ) { ?>
<p class="error">Problemas con formulario</p>
<?php } ?>

<br />

   <?php // echo "<pre>" ; print_r($this->campos) ; echo "</pre>"; // DEV  ?>

   <?php foreach ( $this->campos as $campo => $relacion ) { ?>

    <?php if ( isset($this->campos[$campo]['privado']) && $this->campos[$campo]['privado'] == 1 ) { continue; } ?>

    <?php if ( isset($this->campos[$campo]['oculto_form']) && $this->campos[$campo]['oculto_form'] == 1 ) { ?>
   <?php echo HTML::form_hidden($campo,$this->valores($campo)); ?>
   <?php continue; } ?>

   <?php if ( $relacion != 'ID' && $campo != "fecha_creacion" && $campo != "fecha_modificacion" ) { ?>   

   <div class="caja_campo" id="caja_campo_<?=$campo?>">

   <?php if ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'textarea'  ) { ?>

   <div class="caja_campo_titulo"><?=literal($campo)?></div>

   <?php echo HTML::form_text($campo
         ,$this->valores($campo)
         ,array('rows'=>$this->campos[$campo]['rows'],'cols'=>$this->campos[$campo]['cols'], 'readonly'=>'readonly')
         ,0); 
   ?>
   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'pass_md5' ) { ?>
   
      <?php // si es el campo con contraseña no se presenta ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion'  ) { ?>

      <div class="caja_campo_titulo"><?=literal($this->campos[$campo]['tabla'])?></div>

      <?php echo HTML::form_select($campo, $this->campos[$campo]['opciones'],$this->valores($campo),literal('Seleccionar',1),TRUE); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha' ) { ?>
   
   <div class="caja_campo_titulo"><?=literal($campo)?></div>

   <?php echo HTML::form_fecha($campo,$this->valores($campo),array('readonly'=>'readonly')); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha_hora' ) { ?>
   
   <div class="caja_campo_titulo"><?=literal($campo)?></div>

   <?php 
   $valor = ( $this->valores($campo) && $this->valores($campo) != '0000-00-00 00:00:00' ) 
               ? strftime("%Y-%m-%d %H:%M",strtotime($this->valores($campo))) 
               : strftime("%Y-%m-%d %H:%M"); 
   ?>
   
   <?php echo HTML::form_fecha($campo,$valor,array('readonly'=>'readonly')); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'booleano'  ) { ?>

   <div class="caja_campo_titulo"><?=literal($campo,1)?></div>

   <?php echo HTML::form_bool($campo ,( $this->valores($campo) ) ? TRUE : FALSE,array('readonly'=>'readonly') ); 
   ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'enum'  ) { ?>

   <div class="caja_campo_titulo"><?=literal($campo,1)?></div>

   <?php echo HTML::form_enum($campo ,$this->valores($campo),array('readonly'=>'readonly'),$this->campos[$campo]['opciones']); 
   ?>

   <?php } else { ?>

   <div class="caja_campo_titulo"><?=literal($campo)?></div>

   <?php $atr = FALSE ; ?>
   <?php if ( isset($this->campos[$campo]['maxlength']) ) $atr['maxlength'] = $this->campos[$campo]['maxlength'] ; ?>
   <?php if ( isset($this->campos[$campo]['size']) ) $atr['size'] = $this->campos[$campo]['size'] ; ?>
   <?php $atr['readonly'] = 'readonly'; ?>

   <?php echo HTML::form_text($campo
         ,$this->valores($campo)
         ,$atr); 
   ?>
   <?php } ?>

   <div class="caja_campo_error">
      <?php if ( isset($this->displayHash['PROBLEMS'][$campo]) ) echo $this->displayHash['PROBLEMS'][$campo]; ?>
   </div>

   </div>

   <?php } ?>

   <?php } ?>
