<?php

/**
 * @file registro_visualizar.phtml
 * @brief Plantilla por defecto para mostrar los registros individualmente
 *
 * @ingroup crud
 */

?>

<?php if ( isset($this->displayHash["PROBLEMS"]) ) { ?>
<p class="error">Problemas con formulario</p>
<? } ?>

<br />

   <?php // echo "<pre>" ; print_r($this->campos) ; echo "</pre>"; // DEV  ?>

   <?php foreach ( $this->campos as $campo => $relacion ) { ?>

    <?php if ( isset($this->campos[$campo]['privado']) && $this->campos[$campo]['privado'] == 1 ) { continue; } ?>

    <?php if ( isset($this->campos[$campo]['oculto_form']) && $this->campos[$campo]['oculto_form'] == 1 ) { ?>
   <input type="hidden" name="<?=$campo?>" value="<?=$this->valores($campo)?>" /> 
   <?php continue; } ?>

   <?php if ( $relacion != 'ID' && $campo != "fecha_creacion" && $campo != "fecha_modificacion" ) { ?>   

   <div class="caja_campo" id="caja_campo_<?=$campo?>">

   <?php if ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'textarea'  ) { ?>

   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <textarea readonly="readonly" rows="<?=$this->campos[$campo]['rows']?>" cols="<?=$this->campos[$campo]['cols']?>" name="<?=$campo?>"><?=$this->valores($campo)?></textarea>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'pass_md5' ) { ?>
   
      <?php // si es el campo con contraseña no se presenta ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion'  ) { ?>

      <div class="caja_campo_titulo"><?=literal($this->campos[$campo]['tabla'])?>: </div>
      <select disabled name="<?=$campo?>">
         <option readonly="readonly"><?=literal('Seleccionar')?></option>
         <?php foreach ( $this->campos[$campo]['opciones'] as $res) { ?>
            <?php $count=0; ?>
            <?php foreach ( $res as $contenido ) { ?>
            <?php if ( $count == 0 ) $identificador = $contenido; ?>
            <?php if ( $count == 1 ) $nombre = $contenido; ?>
            <?php $count++; ?>
            <?php } ?>
            <option value="<?=$identificador?>"<?php if ( $identificador == $this->valores($campo) ) echo ' selected' ;?>><?=$nombre?>
            </option>
         <?php } ?>
      </select>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha' ) { ?>
   
   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <input readonly="readonly" name="<?=$campo?>"  type="date" value="<?=str_replace(' ','T',$this->valores($campo))?>"/>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha_hora' ) { ?>
   
   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <input readonly="readonly" name="<?=$campo?>"  type="datetime-local" value="<?php if ( $this->valores($campo) !== '0000-00-00 00:00:00' ) { echo strftime("%Y-%m-%dT%H:%M",strtotime($this->valores($campo))); } else { echo ''; } ?>"/>

   <?php } else { ?>

   <div class="caja_campo_titulo"><?=literal($campo)?>: </div>
   <input readonly="readonly" name="<?=$campo?>" 
      <?php if ( isset($this->campos[$campo]['maxlength']) ) { ?>
      maxlength="<?=$this->campos[$campo]['maxlength']?>" 
      <?php } ?>
      <?php if ( isset($this->campos[$campo]['size']) ) { ?>
      size="<?=$this->campos[$campo]['size']?>" 
      <?php } ?>
      type="text" value="<?=$this->valores($campo)?>"/>

   <?php } ?>

   <div class="caja_campo_error">
      <?php if ( isset($this->displayHash['PROBLEMS'][$campo]) ) echo $this->displayHash['PROBLEMS'][$campo]; ?>
   </div>

   </div>

   <?php } ?>

   <?php } ?>
