<?php

/**
 * @file registros_combinados_editar.phtm
 * @brief Generamos formulario según tipo de campo
 * @ingroup crud
 * @ingroup plantilla_crud
 */

require_once(GCM_DIR.'lib/int/formato/lib/HTML.php');

/** Saber si tenemos que cargar el código para el tratamiento de fechas */

$cargar_codigo_fechas_horas = FALSE;
$dir_codigo_fechas_horas    = GCM_DIR.'lib/int/databoundobject/ext/mugifly-jquery-simple-datetimepicker/';
$cargar_codigo_fechas       = FALSE;
$dir_codigo_fechas          = GCM_DIR.'lib/int/databoundobject/ext/jquery.datepick/';
$dir_codigo_admin_varios    = GCM_DIR.'lib/int/databoundobject/js/';

// Definimos si permitimos modificar los calores del formulario o no
$editable = TRUE;

// echo "<pre>Tabla:  " ; print_r($nombre_tabla_relacionada." contador: $contador") ; echo "</pre>"; // DEV
// echo "<pre>CAMPOS: " ; print_r($this) ; echo "</pre>"; // DEV

?>

<br />

   <div class="caja_registro caja_registro_on" id="caja_registro_<?php echo $nombre_tabla_relacionada ?>-<?php echo $contador ?>">

   <?php // echo "<pre>Tabla:  " ; print_r($nombre_tabla_relacionada." contador: $contador") ; echo "</pre>"; // DEV ?>

   <?php if ( isset($this->ID) ) { ?>
   <?php echo HTML::form_hidden($nombre_tabla_relacionada,$this->ID); ?>
   <?php } ?>

   <?php foreach ( $this->campos as $campo => $relacion ) { ?>

   <?php if ( isset($this->campos[$campo]['oculto_form']) && $this->campos[$campo]['oculto_form'] == 1 ) { ?>
   <?php echo HTML::form_hidden($nombre_tabla_relacionada.'_'.$campo.'[]',$this->valores($campo,$nombre_tabla_relacionada,$contador)); ?>
   <?php continue; } ?>

   <?php if ( isset($this->campos[$campo]['ignorar']) && $this->campos[$campo]['ignorar'] == 1 ) continue; ?>

   <?php if ( $relacion != 'ID' && $campo != "fecha_creacion" && $campo != "fecha_modificacion"  ) { ?>   

   <?php if ( $contador !== FALSE ) { // Si tenemos contador lo añadimos al identificador?>
      <div class="caja_campo" id="caja_campo_<?php echo $nombre_tabla_relacionada; ?>_<?=$campo?>-<?php echo $contador ?>">
   <?php } else { ?>
      <div class="caja_campo" id="caja_campo_<?php echo $nombre_tabla_relacionada; ?>_<?=$campo?>">
   <?php } ?>

   <?php if ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion'  ) { ?>

      <div class="caja_campo_titulo"><?=literal($this->campos[$campo]['tabla'])?></div>
      <?php echo HTML::form_select($nombre_tabla_relacionada.'_'.$campo.'[]', $this->campos[$campo]['opciones']
         ,$this->valores($campo,$nombre_tabla_relacionada,$contador)
         ,literal('Seleccionar')
         ,TRUE); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'relacion_varios'  ) { ?>

   <?php // Tenemos definido un campo que hace referencia a una tabla externa con relaciones multiples ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha' ) { ?>
   
   <?php $cargar_codigo_fechas[] = $campo; ?>
   <div class="caja_campo_titulo"><?=literal($campo,$nombre_tabla_relacionada,$contador)?></div>
   <?php $atr = FALSE; if ( ! $editable ) $atr['readonly'] = 'readonly'; ?>
   <?php echo HTML::form_text($nombre_tabla_relacionada.'_'.$campo.'[]',$this->valores($campo,$nombre_tabla_relacionada,$contador),$atr); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'fecha_hora' ) { ?>
   
   <?php $cargar_codigo_fechas_horas[] = $campo; ?>
   <div class="caja_campo_titulo"><?=literal($campo,$nombre_tabla_relacionada,$contador)?></div>
   <?php 
   $valor = ( $this->valores($campo,$nombre_tabla_relacionada,$contador) && $this->valores($campo,$nombre_tabla_relacionada,$contador) != '0000-00-00 00:00:00' ) 
               ? strftime("%Y-%m-%d %H:%M",strtotime($this->valores($campo,$nombre_tabla_relacionada,$contador))) 
               : strftime("%Y-%m-%d %H:%M"); 
   ?>
   <?php $atr = FALSE; if ( ! $editable ) $atr['readonly'] = 'readonly'; ?>
   <?php echo HTML::form_text($nombre_tabla_relacionada.'_'.$campo.'[]',$valor,$atr); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'pass_md5' ) { ?>
   
   <div class="caja_campo_titulo"><?=literal('contraseña')?></div>
   <?php $atr = FALSE; if ( ! $editable ) $atr['readonly'] = 'readonly'; ?>
   <?php echo HTML::form_pass($nombre_tabla_relacionada.'_'.$campo.'[]',FALSE,$atr); ?>
   </div>
   <div class="caja_campo" id="caja_campo_verificacion">
   <div class="caja_campo_titulo"><?=literal('verificación')?></div>
   <?php echo HTML::form_pass($nombre_tabla_relacionada.'_verificacion[]',FALSE,$atr); ?>

   <?php } elseif ( isset($this->campos[$campo]['tipo']) && $this->campos[$campo]['tipo'] == 'textarea'  ) { ?>

   <div class="caja_campo_titulo"><?=literal($campo,$nombre_tabla_relacionada,$contador)?></div>

   <?php if ( ! $editable ) $atr['readonly'] = 'readonly'; ?>
   <?php if ( $this->campos[$campo]['rows'] ) $atr['rows'] = $this->campos[$campo]['rows']; ?>
   <?php if ( $this->campos[$campo]['cols'] ) $atr['cols'] = $this->campos[$campo]['cols']; ?>

   <?php echo HTML::form_text($nombre_tabla_relacionada.'_'.$campo.'[]'
         ,$this->valores($campo,$nombre_tabla_relacionada,$contador)
         ,$atr
         ,0); 
   ?>

   <?php } else { ?>

   <div class="caja_campo_titulo"><?=literal($campo,$nombre_tabla_relacionada,$contador)?></div>

   <?php $atr = FALSE ; ?>
   <?php if ( isset($this->campos[$campo]['maxlength']) ) $atr['maxlength'] = $this->campos[$campo]['maxlength'] ; ?>
   <?php if ( isset($this->campos[$campo]['size']) ) $atr['size'] = $this->campos[$campo]['size'] ; ?>
   <?php if ( ! $editable ) $atr['readonly'] = 'readonly'; ?>

   <?php echo HTML::form_text($nombre_tabla_relacionada.'_'.$campo.'[]'
         ,$this->valores($campo,$nombre_tabla_relacionada,$contador)
         ,$atr); 
   ?>

   <?php } ?>

   <div class="caja_campo_error">
      <?php if ( isset($this->displayHash['PROBLEMS'][$campo]) ) echo $this->displayHash['PROBLEMS'][$campo]; ?>
   </div>

   </div>

   <?php } ?>

   <?php } ?>

<?php

if ( $objeto_padre ) {

// Cargamos código para el tratamiento de fechas si se ha pedido

$objeto_padre->librerias_js["administrar_registros_varios.js"] = $dir_codigo_admin_varios."administrar_registros_varios.js";

if ( $cargar_codigo_fechas_horas ) {

   $objeto_padre->ficheros_css["jquery.simple-dtpicker.css"] = $dir_codigo_fechas_horas."jquery.simple-dtpicker.css";
   $objeto_padre->librerias_js["jquery.simple-dtpicker.js"] = $dir_codigo_fechas_horas."jquery.simple-dtpicker.js";


   foreach ( $cargar_codigo_fechas_horas as $campo_fecha ) {
      $objeto_padre->codigo_js .= "
         $(function(){
            $('*[name=<?php echo $nombre_tabla_relacionada; ?>_$campo_fecha]').appendDtpicker();
         });
         ";
      }

   }

if ( $cargar_codigo_fechas ) {

   $objeto_padre->ficheros_css['jquery.datepick.css'] = $dir_codigo_fechas.'jquery.datepick.css';
   $objeto_padre->codigo_js .= file_get_contents(dirname(__FILE__).'/../ext/jquery.datepick/jquery.datepick.js');

   foreach ( $cargar_codigo_fechas as $campo_fecha ) {
      $objeto_padre->codigo_js .= "
         $(function() {
            $('#".$campo_fecha."').datepick({dateFormat: 'yyyy-mm-dd'});
         });
         ";
      }

   }
} else {

   registrar(__FILE__,__LINE__,'No hay instancia del objeto padre','ERROR');

   }
?>

<label class="label_check c_on" for="checkbox-01">
<input onclick="var el=document.getElementById('caja_registro_<?php echo $nombre_tabla_relacionada;?>-<?php echo $contador ?>');el.parentNode.removeChild(el);" name="<?php echo $nombre_tabla_relacionada ?>_eliminar-<?php echo $contador ?>" id="<?php echo $nombre_tabla_relacionada ?>_eliminar-<?php echo $contador ?>" type="checkbox" value="1" >
Eliminar
</label>

</div>
