<?php

/**
 * @file formgcmConfigGui.php
 * @brief Plantilla para generar formulario de configuración
 */


function contabilizar_saltos_linea($cadena) {

   //Definimos el ancho que queramos en una variable
   $ancho=55; 

   if (strtoupper(substr(PHP_OS,0,3)=='WIN')) { 
     $eol="\r\n"; 
   } elseif (strtoupper(substr(PHP_OS,0,3)=='MAC')) { 
     $eol="\r"; 
   } else { 
     $eol="\n"; 
      } 

   $cad=wordwrap($cadena, $ancho, $eol, 1); 
   return substr_count($cad,$eol)+1; 

   }

?>
<script type="text/javascript">
   <?php include(dirname(__FILE__).'/../js/GcmConfigGui.js'); ?>
</script>

<form id="formVar_<?php echo $this->idioma ?>" action="" method="POST">

   <div id="cajaForm_<?php echo $this->idioma ?>" class="GcmConfigCajaForm">

      <?php if ( isset($this->variables) ) { while (list($clave, $val)=each($this->variables)){ ?>

      <?php // Si es un array se debe permitir añadir más valores o eliminarlos ?>

      <?php if ( is_array($val)) {  // Puede se una lista o un grupo ?>

      <?php $grupo = ( is_array($val[0]) ) ? 'Grupo' : FALSE ; // Saber si es un grupo ?>

      <div id="elemento_<?php echo $this->idioma ?>-<?php echo $clave?>" class="cajaElemento" >

         <b><?php echo $clave?></b>
         <?php if ( $eliminar ) { ?>
         <a onclick='javascript:eliminarElemento<?php echo $grupo ?>("elemento_<?php echo $this->idioma ?>-<?php echo $clave?>")' >[X]</a>
         <?php   } ?>

         [<a title='<?php echo literal('Añadir más').' '.literal($clave) ?>' href="javascript:anadirVariable<?php echo $grupo ?>('<?php echo $this->idioma ?>','<?php echo $clave ?>',<?php echo count($val);?>)" >+</a>]

      <div>

         <div class="textAreaDescripLLista">

         <?php  
         $cadena=$this->getDescripcion($clave);
         $lineas=contabilizar_saltos_linea($cadena);
         ?> 

         <textarea rows='<?php echo $lineas ?>' name='descripcion_<?php echo $this->idioma ?>[<?php echo $clave ?>]<?php if ( $grupo ) echo '[grupo]'; ?>'
         <?php if ( ! $modificar_descripciones ) { ?>
         class='inputLectura' readonly
         <?php } ?> ><?php echo $cadena?></textarea>

         </div>

         <div id='caja_<?php echo $this->idioma ?>-<?php echo $clave?>'>

            <?php $conta=0; ?>

            <?php while (list($claveArray, $valorArray)=each($val)) { $conta++; ?>

            <?php if ( is_array($valorArray) ) { ?>

            <?php 
            // Si estamos en un grupo no se puede eliminar los items individualmente, pero si se puede
            // añadir o eliminar grupos.
            ?>

            <fieldset class="grupo_config" id="item_<?php echo $clave.'-'.($conta - 1) ?>">

            <legend id="legend_<?php echo $clave.'-'.($conta - 1) ?>">
               <?php echo literal($clave).' ('.($conta - 1) .')'; ?>
               <?php if ( true || $eliminar ) {  // Permitimos eliminar grupo a usuario ?>
               <a title="<?php echo literal('Eliminar').' '.literal($claveArray); ?>" href='javascript:eliminarGrupo("item_<?php echo $clave.'-'.($conta - 1) ?>")' >[X]</a>
               <?php   } ?>
            </legend>

            <?php $conta2=0; ?>

            <?php while (list($claveArray2, $valorArray2)=each($valorArray)) { $conta2++; ?>

            <div id='<?php echo $claveArray."-".$conta2?>' >

               <b><?php echo $claveArray2?></b>
               <?php $cadena =  $this->getDescripcion($claveArray2,NULL,$clave) ?>
               <textarea class="textAreaDescrip" rows='<?php echo contabilizar_saltos_linea($cadena) ?>' name='descripcion_<?php echo $this->idioma ?>[<?php echo $clave ?>][<?php echo $claveArray2 ?>]'

               <?php
               // Solo aactivamos la modificación de las descripciones del último elemento 
               // del grupo, ya que si se modifica las anteriores seria chafada por la última
               ?>

               <?php if ( ! $modificar_descripciones || $conta != count($val) ) { ?>
               class='inputLectura' readonly
               <?php } ?> ><?php echo $cadena;?></textarea>

               <textarea class="item_valor formulari2 textAreaValor" rows='1' name='escribir_<?php echo $this->idioma ?>[<?php echo $clave ?>][<?php echo $claveArray?>][<?php echo $claveArray2 ?>]' ><?php echo $valorArray2?></textarea>

            </div>


            <?php } /// Acaba while ?>

            </fieldset>

            <?php } else { // No es un array ?>

            <div id='<?php echo $clave."-".$conta?>' >

               <?php if ( 0 !== $conta ) { ?>
               [<a href="javascript:eliminarVariable('<?php echo $clave?>-<?php echo $conta?>')" >-</a>]
               <?php } ?>
               <br />
               <textarea class="formulari2" rows='1' name='escribir_<?php echo $this->idioma ?>[<?php echo $clave?>][]' ><?php echo $valorArray?></textarea>

            </div>
            <?php } // Acaba si es un array ?>

            <?php } // Acaba while de array ?>

         </div>

         <?php } else { ?>


         <div id="elemento_<?php echo $this->idioma ?>-<?php echo $clave?>" class="cajaElemento" >

            <b><?php echo $clave?></b>
            <?php if ( $eliminar ) { ?>
            <a onclick='javascript:eliminarElemento("elemento_<?php echo $this->idioma ?>-<?php echo $clave?>")' >[X]</a>
            <?php   } ?>

         <div>

         <?php  
         $cadena=$this->getDescripcion($clave);
         $lineas=contabilizar_saltos_linea($cadena);
         ?> 

         <textarea class="textAreaDescrip" rows='<?php echo $lineas ?>' name='descripcion_<?php echo $this->idioma ?>[<?php echo $clave ?>]'
         <?php if ( ! $modificar_descripciones ) { ?>
         class='inputLectura' readonly
         <?php } ?> ><?php echo $cadena?></textarea>

         <textarea class="textAreaValor formulari2" rows='1' name='escribir_<?php echo $this->idioma ?>[<?php echo $clave?>]' ><?php echo $val?></textarea>

         <?php } ?>

	</div>
      <hr class="clear" />
   </div>

      <?php } ?>

      <?php } else { // No tenemos array valido ?>
      <p class="error"><?php echo literal("Sin contenido",3)?></p>
      <?php } ?>
   </div>

   <?php if ( $ampliar ) { ?>

   <br /><br />
   <a class='boton' onclick="javascript:nuevaVariable('<?php echo $this->idioma ?>'); return false;">Añadir nuevo elemento </a>

   <?php } ?>

   <br /><br />

   <input type='hidden' name='archivo' value='<?php echo $this->archivo ?>' />
   <input type='hidden' name='idioma' value='<?php echo $this->idioma ?>' />
   <input type='hidden' name='accion' value='escribir_gcmconfig' />
   <input type="submit" value="Enviar cambios" />

</form>
