<?php

/**
 * @file principal.phtml
 * @brief Menú en formato tabla
 * @ingroup plantilla_menu
 */

// Ordenamos campos por su peso
if ( $elementos ) uasort($elementos, array("Menu", 'ordenar_por_peso'));

?>

<ul id="menu">

<?php if ( isset($this->opciones['ocultar_inicio']) && $this->opciones['ocultar_inicio'] == 1 ) { ?>

   <!-- Sin enlace a inicio -->

<?php } else { // Acaba ocultar inicio ?>

<?php if("inicio" == $this->actual ) {  // Elemento inicio no actual ?>

      <li id="menuOff">
         <a href="<?php echo Router::$base?>">
            <?php echo literal('inicio',1); ?>
         </a>
      </li>

<?php } else { // Acaba si estamos en inicio ?>

      <li>
         <a href="<?php echo Router::$base;?>">
            <?php echo literal('inicio',1);?>
         </a>
      </li>	 

<?php } // Acaba no estamos en inicio ?>

<?php } // Acaba no se oculta inicio ?>

<?php foreach($elementos as $elemento) { // Vamos recorriendo las opciones existentes ?>

   <?php $nombre = basename($elemento); ?>

<?php if ( is_dir(Router::$dd.$elemento) ) { ?>

<?php if ( $elemento == $this->actual ) { // si es la opción actual ?>

   <li id="menuOff">
         <?php echo literal($elemento,1);?>
   </li>

<?php } else {  // Acaba es la opción actual ?>

      <li id="<?php echo $elemento ?>" >
         <a href="<?php echo Router::$base.$elemento ?>" >
            <?php echo literal($elemento,1)?>
         </a>
      </li>

<?php } ?>

<?php } ?>

<?php } ?>

</ul> 
