<?php

/**
 * @file totbisbal/trepa.phtml
 * @brief Plantilla para presentar las imagenes con totbisbal
 * @ingroup galeria
 * @ingroup plantilla_galeria
 *
 * Es necesario que la pagina que presente las imagenes incluya los scripts y css
 *
 * <script src="../moduls/galleria/themes/classic/galleria.classic.min.js"></script>
 *
 * Exemple:
 *
 * <div id="gallery">
 *  <a rel="img/big1.jpg" href="/img/large1.jpg"><img src="/img/thumb1.jpg" alt="My description" title="My title"></a>
 *  <a rel="img/big2.jpg" href="/img/large2.jpg"><img src="/img/thumb2.jpg" alt="Another text" title="Another title"></a>
 * </div>
 */

?>
<?php if ( $this->count() > 0 ) { ?>

   <div id="gallery">

   <?php for ($i=0;$i<$this->count();$i++){ ?>

   <?php $sql="SELECT titol, subtitol FROM galeries_fotos_imatges WHERE galeries_fotos_id = ".
         $_REQUEST['galeries_fotos_id']. " AND nom = '".$this->imatges[$i]->getId()."'"; ?>
   <?php $rs = mysql_query($sql) ; $row = mysql_fetch_array($rs) ; list($titol, $subtitol) = $row; ?> 

   <a rel="<?php echo DIR_BASE.$this->imatges[$i]->getSrc();?>" 
      href="<?php echo DIR_BASE.$this->imatges[$i]->getSrc();?>">
      <img src="<?php echo DIR_BASE.$this->imatges[$i]->getMiniaturaSrc();?>" 
      title="<?php echo $titol?>" 
      alt="<?php echo $subtitol?>" />
   </a>

   <?php } ?>

   </div>

<?php } ?>

<script src="<?php echo DIR_BASE?>moduls/galeria3/moduls/galleria/galleria-1.2.6.js" type="text/javascript"></script>
<script src="<?php echo DIR_BASE?>moduls/galeria3/moduls/galleria/themes/totbisbal/galleria.classic.js" type="text/javascript"></script>

<script type='text/javascript'>
   $("#gallery").galleria({
       width: 800,
       height: 533
   });
</script>
