<?php

/**
 * @file popeye/trepa.phtml 
 * @brief Plantilla para presentar las imagenes con popeye
 * @ingroup galeria
 * @ingroup plantilla_galeria
 *
 * Es necesario que la pagina que presente las imagenes incluya los scripts y css
 *
 * <script src="../moduls/galleria/themes/classic/galleria.classic.min.js"></script>
 *
 * Exemple:
 *
 * <div id="gallery">
 *  <a rel="img/big1.jpg" href="/img/large1.jpg"><img src="/img/thumb1.jpg" alt="My description" title="My title"></a>
 *  <a rel="img/big2.jpg" href="/img/large2.jpg"><img src="/img/thumb2.jpg" alt="Another text" title="Another title"></a>
 * </div>
 */

?>

<?php if ( $this->count() > 0 ) { ?>

        <div class="ppy" id="ppy1">
            <ul class="ppy-imglist">

   <?php for ($i=0;$i<$this->count();$i++){ ?>

   <?php $titol = "TITOL"; ?>
   <?php $subtitol = "SUBTITOL"; ?>

       <li>
           <a href="<?php echo $this->dir_base.$this->imatges[$i]->getSrc();?>">
               <img src="<?php echo $this->dir_base.$this->imatges[$i]->getMiniaturaSrc();?>" alt="" />
           </a>
           <span class="ppy-extcaption">
               <!-- <strong><?php echo $titol?></strong><br /><?php echo $subtitol?><br /> -->
               <a href="<?php echo $this->dir_base.$this->imatges[$i]->getSrc();?>">Ampliar</a>
           </span>
       </li>

   <?php } ?>

         </ul>
            <div class="ppy-outer">
                <div class="ppy-stage">
                    <div class="ppy-nav">
                        <a class="ppy-prev" title="Previous image">Previous image</a>
                        <a class="ppy-switch-enlarge" title="Enlarge">Enlarge</a>
                        <a class="ppy-switch-compact" title="Close">Close</a>
                        <a class="ppy-next" title="Next image">Next image</a>
                    </div>
                </div>
            </div>
            <div class="ppy-caption">
                <div class="ppy-counter">
                    Image <strong class="ppy-current"></strong> of <strong class="ppy-total"></strong> 
                </div>
                <span class="ppy-text"></span>
            </div>

      </div>

<?php } ?>

<!--
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_base.$this->dir_mod?>moduls/popeye/lib/popeye/jquery.popeye-2.1.js"></script>
-->

<?php

$this->carga_js = "

  $('#ppy1').popeye();

";
?>
