<?php
require_once 'PHPUnit/Framework.php';

require_once '/home/eduardo/SERVIDOR/subversion/gcm/trunk/gcm/modulos/temas/lib/TemaGcm.php';

/**
 * Test class for TemaGcm.
 * Generated by PHPUnit on 2010-10-25 at 11:59:31.
 */
class TemaGcmTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TemaGcm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TemaGcm();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement test_construct().
     */
    public function test_construct()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIncluir_javascript().
     */
    public function testIncluir_javascript()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testColor().
     */
    public function testColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testConstruir_css().
     */
    public function testConstruir_css()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testConstruir_js().
     */
    public function testConstruir_js()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRuta().
     */
    public function testRuta()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDevolver_colores_faltantes().
     */
    public function testDevolver_colores_faltantes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
