<?php

/** 
 * @file heads.html
 * @brief Head de la plantilla
 * @ingroup plantilla_metatags
 */

 ?>

<title><?php echo $titulo; ?></title>

<!-- icono -->
<link type="image/x-icon" href="favicon.ico" rel="shortcut icon" />

<!-- metatags -->
<meta name="description" content="<?php echo htmlentities($metatags['description'], ENT_QUOTES, "UTF-8") ?>">
<meta name="keywords" content="<?php echo htmlentities(implode(',',$metatags['keywords']), ENT_QUOTES, "UTF-8") ?>">
<meta name="author" content="<?php echo $metatags['author'] ?>">
<meta name="generator" content="<?php echo $metatags['generator'] ?>">
<meta name="robots" content="<?php echo $metatags['robots'] ?>">

<!-- geolocalización -->
<meta name="geo.position" content="<?php echo $metatags['geo.position'] ?>">
<meta name="geo.placename" content="<?php echo $metatags['geo.placename'] ?>">
<meta name="geo.region" content="<?php echo $metatags['geo.region'] ?>">

<!-- dublincore -->
<meta name="DCTERMS.created" content="2011-01-01">
<meta name="DC.title" content="<?php echo $metatags['name'] ?>">
<meta name="DC.description" content="<?php echo htmlentities($metatags['description'], ENT_QUOTES, "UTF-8") ?>">
<meta name="DCTERMS.subject" content="<?php echo htmlentities($metatags['subject'], ENT_QUOTES, "UTF-8") ?>">
<meta name="DC.language" content="<?php echo Router::$i ?>">
<meta name="DC.creator" content="<?php echo $metatags['author'] ?>">
<meta name="DC.license" content="<?php echo $metatags['license'] ?>">
<meta name="DC.type" content="<?php echo $metatags['type'] ?>">
<meta name="DC.Publisher" content="<?php echo $metatags['generator'] ?>">

<!-- Otros -->
<link rel="image_src" href="<?php echo Router::$base.$metatags['image'] ?>" />

