<?php

/** 
 * @file redes_sociales.phtml
 * @brief Plantilla para Redes_sociales
 * @ingroup plantilla_redes_sociales
 */


?>

   <img alt="twitter" src="<?php echo Router::$base.$gcm->event->instancias['temas']->ruta('redes_sociales','iconos','twitter.png') ?>" />

   <img alt="facebook" src="<?php echo Router::$base.$gcm->event->instancias['temas']->ruta('redes_sociales','iconos','facebook.png') ?>" />

   <img alt="pic" src="<?php echo Router::$base.$gcm->event->instancias['temas']->ruta('redes_sociales','iconos','tripadvisor.png') ?>" />

