<?php

/** 
 * @file slide.phtml
 * @brief Slide de imágenes
 * @ingroup plantilla_responsiveslides
 */

 ?>
<ul class="rslides">
   <li>
  <video poster="<?php // echo Router::$dd.$this->imagenes ?>/masmonell-poster.png" controls tabindex="0">
    <source src="<?php echo Router::$dd.$this->imagenes ?>/masmonell.webm" type='video/webm; codecs="vp8, vorbis"'/>
    <source src="<?php echo Router::$dd.$this->imagenes ?>/masmonell.mp4" />
    I'm sorry; your browser doesn't support HTML5 video.
  </video>
  </li>
   <?php foreach( $imagenes as $img ) {  ?>
   <li><img src="<?php echo $img ?>" alt="MasMonell"></li>
   <?php } ?>
</ul>
<!--
<b class="play_slider">Play</b>
<b class="pause_slider">Pause</b>
-->
<script>
   addLoadEvent(function(){
      $(function() {

         $(".rslides").responsiveSlides({
           auto: true,             // Boolean: Animate automatically, true or false
           //speed: 1500,            // Integer: Speed of the transition, in milliseconds
           speed: 500,            // Integer: Speed of the transition, in milliseconds
           timeout: 8000,          // Integer: Time between slide transitions, in milliseconds
           pager: true,           // Boolean: Show pager, true or false
           nav: true,             // Boolean: Show navigation, true or false
           random: false,          // Boolean: Randomize the order of the slides, true or false
           pause: true,           // Boolean: Pause on hover, true or false
           pauseControls: true,    // Boolean: Pause when hovering controls, true or false
           // prevText: "Previous",   // String: Text for the "previous" button
           // nextText: "Next",       // String: Text for the "next" button
           maxwidth: "900",           // Integer: Max-width of the slideshow, in pixels
           // navContainer: "",       // Selector: Where controls should be appended to, default is after the 'ul'
           // manualControls: "",     // Selector: Declare custom pager navigation
           // namespace: "rslides",   // String: Change the default namespace used
           namespace: "centered-btns"
           // before: function(){},   // Function: Before callback
           // after: function(){},     // Function: After callback
         });

      });
   });
</script>
