<?php

/** 
 * @file info.phtml
 * @brief Plantilla para Aplicar_SEO
 * @ingroup plantilla_aplicar_SEO
 */

 ?>
<div class="admin">
Pendiente de hacer que este módulo compruebe y ayude a tener lo necesario para un buen
posicionamineto.
<br /><br />
- Creción de sitemap.xml
</div>

<h2>Cosas a tener en cuenta</h2>

<ul>
   <li>Comprobar si estamos dados de alta en <a href="http://www.dmoz.org/search?q=<?php echo $datos['dominio'];?>" target="_blank" >http://www.dmoz.org</a></li>
   <li>Comprobar si nos indexa <a href="http://es.search.yahoo.com/search?p=site:<?php echo $datos['dominio'];?>&fr=sfp&fr2=&iscqry=" target="_blank" >yahoo</a></li>
   <li>Comprobar si nos indexa <a href="https://www.google.es/search?q=site%3A<?php echo $datos['dominio'];?>&fr=sfp&fr2=&iscqry=" target="_blank" >google</a></li>
   <li>Mientras no tengamos un sitemap propio podemos utilizar <a href="http://tools.pingates.com/sitemap">pingates</a> para generarlo automáticamente a los diferentes buscadores</li>
</ul>

<h2>Metatags</h2>

<p>Los metatags son generados desde el módulo <a href="<?php echo Router::$base;?>metatags/configuracion">metatags</a></p>

<h2>Posicionar las palabras claves</h2>

<p>
Tratamiento que hacen los buscadores con las palabras claves
<br />
Google da más importancia a las etiquetas,etc.. que a los meta-tags description y keywords.
<br />
De las cosas que valora más google es que la palabra clave se encuentre en la misma url, el título o en el mismo contenido de la página.
</p>

<h2>Herramientas</h2>
<ul>
   <li>
      <p class="first"><a href="http://www.ranks.nl/cgi-bin/ranksnl/spider/spider.cgi">Keyword density  analyzer</a></p>
      <p>Nos permite ver la relevancia de las palabras clave en nuestra p&aacute;gina.</p>
   </li>
   <li>
      <p class="first"><a href="http://www.google.com/trends">Google trends</a></p>
      <p>Nos permite saber la popularidad por diferentes b&uacute;squedas</p>
   </li>
   <li>
      <p class="first"><a href="https://www.google.com/analytics">Google Analytics</a></p>
      <p>Para estad&iacute;sticas.</p>
   </li>
   <li>
      <p class="first"><a href="https://developers.google.com/speed/pagespeed/insights#url='.$url.'&mobile=false" >Test de velocidad</a></p>
      <p>La velocidad a la que carga la página es importante</p>
   </li>
            
   <li>
      <p class="first"><a href="http://www.google.com/insights/search">Google Insight Search</a></p>
      <p>Conocer las tendencias de busquedasen google.</p>
   </li>
</ul>

<h2>
Más Información sobre SEO
</h2>

<ul>
   <li>
      <a href="http://www.mistrucos.net/truco-google-como-posicionar-una-pagina-web-755_1.htm">
      Como posicionar una p&aacute;gina web
      </a>
   </li>
   <li>
      <a href="http://mamedu.com/gcm/apuntes/programacion/SEO/">
      http://mamedu.com/gcm/apuntes/programacion/SEO/
      </a>
   </li>
</ul>
