<?php

/**
 * @file piulades_zoomer/trepa.phtml
 * @brief Plantilla para presentar las imágenes con zoomer
 * @ingroup galeria
 * @ingroup plantilla_galeria
 */
?>

<!--[if IE 6]>
	<style type="text/css" media="screen">
	ul.thumb li img.hover {
	margin-top:15px;
	background:url(thumb_bg.gif) no-repeat center center;
	border: none;
}
ul.thumb li .title{color:#fff;width:185px;height:50px;margin:0;font-weight:900;background:url(title.gif) no-repeat center center;padding:17px 0 0 0;text-align:center;}
	</style>
<![endif]-->
<style type="text/css">

ul.thumb {float: left;list-style: none;margin: 0; padding: 10px;width: 400px;background-color: white;}
ul.thumb li {margin: 0; padding: 5px;float: left;position: relative;width: 110px;height: 110px;}
ul.thumb li img {width: 100px; height: 100px;border: 1px solid #ddd;padding: 5px;background: #f0f0f0;position: absolute;left: 0; top: 0;-ms-interpolation-mode: bicubic; }
ul.thumb li img.hover {margin-top:15px;background:url(<?php echo $this->dir_mod;?>moduls/zoomer/zoomer/thumb_bg.png) no-repeat center center;border: none;}
.title{position:absolute;width:185px;margin:0;padding: 4px;font-weight:700;background:black no-repeat center center;padding:17px 0 0 0;text-align:center; color: #fff; }

</style> 

<ul class="thumb">
         <?php
         global $vComentari;
         if ( $this->count() > 0 ) {
            for ($i=0;$i<$this->count();$i++){
               $src = $this->dir_base.$this->imatges[$i]->getSrc();
               ?>
               <li>
                  <a href="<?php echo $src?>"><img src="<?php echo $src;?>" alt="<?php echo htmlentities($this->atributs['alt'])?>" />
                  </a>
               </li>
               <?php } ?>
            <?php } ?>
</ul>

<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="<?php echo $this->dir_base.$this->dir_mod;?>moduls/zoomer/zoomer/zoomer.js"></script> 
<script type="text/javascript">
$(document).ready(function(){
 	$('ul.thumb li').Zoomer({speedView:200,speedRemove:400,altAnim:true,speedTitle:800,debug:false});
});
</script>
