<?php
// Call AutentificacionTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "AutentificacionTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once '../lib/Autentificacion.php';

/** Simuladmos sessión para el test */

$_SESSION = array();

/**
 * Test class for Autentificacion.
 * Generated by PHPUnit_Util_Skeleton on 2010-04-29 at 12:26:26.
 */
class AutentificacionTest extends PHPUnit_Framework_TestCase {

   private $pdo;
   private $au;

    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("AutentificacionTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {

       if ( file_exists('/tmp/au.db')  ) unlink('/tmp/au.db');

       $this->pdo = new PDO('sqlite:/tmp/au.db');
       $this->au  = new Autentificacion($this->pdo);

       }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
       if ( file_exists('/tmp/au.db')  ) unlink('/tmp/au.db');
       }

    public function testCrear_tabla() {
       $this->assertTrue(file_exists('/tmp/au.db'), 'Archivo de registro creado');
       }

    public function testEntrar() {

       global $_SESSION;

       $this->assertTrue($this->au->entrar('admin','admin'), 'Archivo de registro creado');
       }

    public function testLogeado() {

       global $_SESSION;

       $this->assertEquals($this->au->logeado(),1,'Hay sesión activa');
       }

    public function testEs_admin() {

       global $_SESSION;

       $this->assertTrue($this->au->es_admin(),'Hay sesión activa');

       }

   }

// Call AutentificacionTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "AutentificacionTest::main") {
    AutentificacionTest::main();
}
?>
